model = "F5-TTS"
ref_audio = "/home/hope/Files/Hackathon/AISalesman/data/vocals/Srishti_greeting.wav"
ref_text = "Hey myself Srishti speaking from study centre. How are you today?"
gen_text = "That's great to hear you're feeling well today. Now, let's talk about your academic goals and how we can support you in achieving them. What subjects do you find most challenging in your current preparation?"
gen_file = ""
remove_silence = false
output_dir = "gen"
output_file = "infer_cli_basic.wav"
